### ISSUE TITLE
API change in Bamboo v5.14.x.x

### ISSUE THREAD

**Issue by bsterner** [drscream/bamboozled-ruby-plugin#23]
Installed the plugin through the marketplace, tried to configure a plan through the "Miscellaneous" tab and got a 500 Server error.  The stacktrace shows...

```
Caused by: java.lang.NoSuchMethodError: com.atlassian.bamboo.v2.build.BaseBuildConfigurationAwarePlugin.isConfigurationMissing(Lcom/atlassian/bamboo/ww2/actions/build/admin/create/BuildConfiguration;)Z
        at com.alienfast.bamboozled.ruby.config.RubyBuildConfigurationPlugin.isConfigurationMissing(RubyBuildConfigurationPlugin.java:90)
        at com.atlassian.bamboo.ww2.actions.build.admin.config.ConfigureBuildMiscellaneousOptions.execute(ConfigureBuildMiscellaneousOptions.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:892)
        at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1537)
```

Looks like the newest version of Bamboo doesn't reference these classes anymore.

Thanks

**Comment by louisnayegon** [comment]
Is there any movement on this our should I revert to an older version of Bamboo?

**Comment by rosskevin** [comment]
Ask in the PR, I had no response to my question on stability.

**Comment by drscream** [comment]
I'm sorry I missed to answer the PR! At the moment everything is stable but I assume I need to fix the `public boolean isApplicableTo(@NotNull ImmutablePlan plan)` to be future compatible.

**Comment by drscream** [comment]
As it's confirmed from @unRARed it would be nice if @rosskevin could merge the pull request and create an official release :-)

**Comment by drscream** [comment]
The fix has been published on the marketplace, if you detect any issue let me know.

- https://marketplace.atlassian.com/plugins/com.alienfast.bamboozled.ruby.bamboozled-ruby-plugin/server/overview
- https://github.com/drscream/bamboozled-ruby-plugin/pull/24
